Interfaz
Brightcoders-Bootcamps/kata-05-reservacion-vuelo-team-01-kata-05 pull request #4
Opened 2020-10-20 18:53 UTC by alcamk

# Description
What did you implemented/Why did you implemented this:
Initial setup
Create the reac-native folder
Folder distribution for components  
Check the correct execution of the deploy in android enviornment 
This is related to the issue number #3 
 
 Examples:
none
 
 # Testing
Git clone project
Run npm install 
Run initial deploy on android (iOS pending)   

 Example:
  none 
  ## Screenshots 
none

2020-10-20 19:29 UTC, OwenRamire requested changes
When you create your setup, just delete all the things that you think you won't use or just delete the code lines on App.js and do:

- `git add .`
- `git commit -m "React Native init" or Initial commit`
on your master branch.

2020-10-20 19:29 UTC, OwenRamire commented on setup/ReservacionVuelo/App.js
> +import React from 'react';
Delete all the code lines or you could leave something like this:
```javascript
import React from 'react';
import {SafeAreaView, Text, StyleSheet} from 'react-native';

const App = () => {
   return (
      <SafeAreaView style={{flex: 1, justifyContent: 'center', alignItems: 'center'}}>
         <Text>Hello world</Text>
      </SafeAreaView>
   );
}

export default App;
```

2020-10-20 19:35 UTC, OwenRamire approved these changes, later dismissed

2020-10-21 15:45 UTC, develiasdaniel approved these changes, later dismissed
Reviewed! ok initial configuration

2020-10-21 15:52 UTC, oswaldotovar32 approved these changes

2020-10-21 16:02 UTC, merged